require("plugin-setup")
require("core.options")
require("core.keymaps")
require("core.colorscheme")
require("plugin.nvim-tree")
require("plugin.lualine")
require("plugin.nvim-cmp")
require("plugin.lsp.mason")
